import { randomUUID } from 'node:crypto'
import { lstat, mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { PandaError, PANDA_ERROR_CODES } from '@panda/contracts'
import type { WorkspaceCapability, WorkspaceHandle, WorkspaceProvider } from '@panda/contracts'

const LOCAL_CAPABILITIES: readonly WorkspaceCapability[] = ['read', 'write']

// Workspace directory names are generated by create() (UUIDs); acquire() only ever
// joins this shape under rootDir. Windows reserved device names are rejected so an
// id can never name a device instead of a workspace directory.
//
// EXPORTED for `removal.ts`, which joins a caller's argv under the same rootDir
// and must accept exactly the same ids this does. Two spellings of "what is a
// workspace id" is how a removal verb comes to reach somewhere `acquire` never
// could.
export const WORKSPACE_ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]*$/
export const WINDOWS_RESERVED_IDS = /^(con|prn|aux|nul|com[1-9]|lpt[1-9])$/i

/**
 * The durable proof that a local workspace directory is panda's (spec M27.A, D2).
 *
 * It lives INSIDE the workspace directory, at {@link LOCAL_WORKSPACE_RECORD_FILE},
 * where the git-worktree ledger deliberately puts its own records in a sibling
 * store instead. That refusal (`ledger.ts:66-78`) is about a file showing up as
 * untracked in `git status`; a local workspace is not a checkout and has no
 * `git status`. What the in-directory placement buys is that the proof and the
 * thing it proves are removed by ONE operation, so no intent file, no liveness
 * check and no interrupted state exist for this store at all.
 *
 * It is DECLARED here, beside the only code that writes it, so the reader in
 * `removal.ts` cannot describe a shape different from the one panda emits.
 */
export interface LocalWorkspaceRecord {
  readonly version: 1
  readonly id: string
  /** Absolute path of the workspace directory, as it was when panda made it. */
  readonly path: string
  readonly createdAt: string
}

/** The record's file name inside the workspace directory. */
export const LOCAL_WORKSPACE_RECORD_FILE = '.panda-workspace.json'

export interface LocalWorkspaceProviderOptions {
  /** Directory under which one subdirectory per workspace is created on demand. */
  readonly rootDir: string
}

interface Lease {
  released: boolean
}

/**
 * Local-directory WorkspaceProvider. The filesystem is the registry: a workspace
 * is a subdirectory of rootDir, so state written into a workspace survives
 * release + re-acquire and provider restarts alike.
 *
 * Release semantics are per handle (matching the port's intentional lease model):
 * each issued handle may be released exactly once — two simultaneously-live
 * handles to one workspace are independent leases — and releasing the SAME handle
 * twice raises PANDA_CONTRACT_WORKSPACE_DOUBLE_RELEASE.
 *
 * dispose() stops the provider; it is idempotent and deliberately leaves every
 * workspace directory in place. After dispose(), every operation — including
 * release() of outstanding handles — raises PANDA_CONTRACT_PROVIDER_DISPOSED.
 */
export class LocalWorkspaceProvider implements WorkspaceProvider {
  readonly #rootDir: string
  #disposed = false
  readonly #leases = new WeakMap<WorkspaceHandle, Lease>()

  constructor(options: LocalWorkspaceProviderOptions) {
    if (typeof options?.rootDir !== 'string' || options.rootDir.trim().length === 0) {
      throw new PandaError(
        PANDA_ERROR_CODES.contractWorkspaceInvalidHandle,
        'LocalWorkspaceProvider requires a non-empty string rootDir',
      )
    }
    this.#rootDir = options.rootDir
  }

  /**
   * Makes the directory, then writes the ownership record INTO it.
   *
   * That order, and the record is not optional: `panda workspace remove` removes
   * a directory if and only if it holds this file (D2), so a create that skipped
   * it would hand back a workspace panda could never take back. A crash between
   * the two lines leaves a directory with no record, which is the same state
   * every workspace made before M27.A is in — reported, never removed (D5).
   *
   * ponytail: a plain `writeFile`, not the ledger's temp-file-then-rename. That
   * one is atomic because it overwrites a store whose previous contents must
   * never be half-replaced; this writes ~150 bytes ONCE into a directory panda
   * created three lines earlier, where a torn write needs a machine crash rather
   * than a kill. Upgrade path: write `<file>.tmp` and rename, if a torn record is
   * ever actually observed. A record a USER corrupted is reported and refused
   * either way (E8), and no atomic write would change that.
   */
  async create(): Promise<WorkspaceHandle> {
    this.#assertActive()
    const id = randomUUID()
    const rootPath = join(this.#rootDir, id)
    const record: LocalWorkspaceRecord = {
      version: 1,
      id,
      path: rootPath,
      createdAt: new Date().toISOString(),
    }
    try {
      await mkdir(rootPath, { recursive: true })
      await writeFile(
        join(rootPath, LOCAL_WORKSPACE_RECORD_FILE),
        `${JSON.stringify(record, null, 2)}\n`,
        'utf8',
      )
    } catch (error) {
      throw this.#wrapIoFailure('create', error)
    }
    return this.#issue(id, rootPath)
  }

  async acquire(id: string): Promise<WorkspaceHandle> {
    this.#assertActive()
    // `typeof id !== 'string'` FIRST, and it is not redundant with the pattern:
    // `RegExp.prototype.test` stringifies its argument, so `test(null)` matches
    // "null" and answers true. Without this the value reached `join()` below and
    // left as an uncoded `TypeError [ERR_INVALID_ARG_TYPE]` out of a port whose
    // whole contract is coded refusals (AD-7). Pinned by the shared
    // `acquire-non-string-id-rejected` clause, so both providers answer alike.
    if (typeof id !== 'string' || !WORKSPACE_ID_PATTERN.test(id) || WINDOWS_RESERVED_IDS.test(id)) {
      this.#failUnknownId(id)
    }
    const rootPath = join(this.#rootDir, id)
    // lstat (not stat): symlinks under rootDir are classified unknown, never followed.
    let info: Awaited<ReturnType<typeof lstat>>
    try {
      info = await lstat(rootPath)
    } catch (error) {
      if ((error as NodeJS.ErrnoException)?.code === 'ENOENT') this.#failUnknownId(id)
      throw this.#wrapIoFailure('acquire', error)
    }
    if (info.isSymbolicLink() || !info.isDirectory()) this.#failUnknownId(id)
    return this.#issue(id, rootPath)
  }

  async release(handle: WorkspaceHandle): Promise<void> {
    this.#assertActive()
    const lease =
      typeof handle === 'object' && handle !== null ? this.#leases.get(handle) : undefined
    if (!lease) {
      throw new PandaError(
        PANDA_ERROR_CODES.contractWorkspaceInvalidHandle,
        'release() only accepts workspace handles issued by this provider',
      )
    }
    if (lease.released) {
      throw new PandaError(
        PANDA_ERROR_CODES.contractWorkspaceDoubleRelease,
        `workspace '${handle.id}' has already been released through this handle`,
      )
    }
    lease.released = true
  }

  // Idempotent: workspace state outlives the provider, so there is nothing to undo.
  async dispose(): Promise<void> {
    this.#disposed = true
  }

  // Every handle gets its own frozen capabilities copy — no shared mutable array.
  #issue(id: string, rootPath: string): WorkspaceHandle {
    const handle: WorkspaceHandle = Object.freeze({
      id,
      rootPath,
      capabilities: Object.freeze([...LOCAL_CAPABILITIES]),
    })
    this.#leases.set(handle, { released: false })
    return handle
  }

  #assertActive(): void {
    if (this.#disposed) {
      throw new PandaError(
        PANDA_ERROR_CODES.contractProviderDisposed,
        'workspace provider has been disposed and no longer serves workspaces',
      )
    }
  }

  // `unknown`, matching GitWorktreeWorkspaceProvider: the guard above admits a
  // non-string here on purpose, and a template literal over it would be a second
  // implicit coercion where the first one was the defect.
  #failUnknownId(id: unknown): never {
    throw new PandaError(
      PANDA_ERROR_CODES.contractWorkspaceUnknownId,
      `unknown workspace id '${String(id)}'`,
    )
  }

  #wrapIoFailure(operation: string, error: unknown): PandaError {
    return new PandaError(
      PANDA_ERROR_CODES.contractWorkspaceUnavailable,
      `workspace provider ${operation} failed on filesystem '${this.#rootDir}': ${error instanceof Error ? error.message : String(error)}`,
      { cause: error },
    )
  }
}
