import { randomUUID } from 'node:crypto'
import { lstat, mkdir } from 'node:fs/promises'
import { join } from 'node:path'
import { PandaError, PANDA_ERROR_CODES } from '@panda/contracts'
import type { WorkspaceCapability, WorkspaceHandle, WorkspaceProvider } from '@panda/contracts'

const LOCAL_CAPABILITIES: readonly WorkspaceCapability[] = ['read', 'write']

// Workspace directory names are generated by create() (UUIDs); acquire() only ever
// joins this shape under rootDir. Windows reserved device names are rejected so an
// id can never name a device instead of a workspace directory.
const WORKSPACE_ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]*$/
const WINDOWS_RESERVED_IDS = /^(con|prn|aux|nul|com[1-9]|lpt[1-9])$/i

export interface LocalWorkspaceProviderOptions {
  /** Directory under which one subdirectory per workspace is created on demand. */
  readonly rootDir: string
}

interface Lease {
  released: boolean
}

/**
 * Local-directory WorkspaceProvider. The filesystem is the registry: a workspace
 * is a subdirectory of rootDir, so state written into a workspace survives
 * release + re-acquire and provider restarts alike.
 *
 * Release semantics are per handle (matching the port's intentional lease model):
 * each issued handle may be released exactly once — two simultaneously-live
 * handles to one workspace are independent leases — and releasing the SAME handle
 * twice raises PANDA_CONTRACT_WORKSPACE_DOUBLE_RELEASE.
 *
 * dispose() stops the provider; it is idempotent and deliberately leaves every
 * workspace directory in place. After dispose(), every operation — including
 * release() of outstanding handles — raises PANDA_CONTRACT_PROVIDER_DISPOSED.
 */
export class LocalWorkspaceProvider implements WorkspaceProvider {
  readonly #rootDir: string
  #disposed = false
  readonly #leases = new WeakMap<WorkspaceHandle, Lease>()

  constructor(options: LocalWorkspaceProviderOptions) {
    if (typeof options?.rootDir !== 'string' || options.rootDir.trim().length === 0) {
      throw new PandaError(
        PANDA_ERROR_CODES.contractWorkspaceInvalidHandle,
        'LocalWorkspaceProvider requires a non-empty string rootDir',
      )
    }
    this.#rootDir = options.rootDir
  }

  async create(): Promise<WorkspaceHandle> {
    this.#assertActive()
    const id = randomUUID()
    const rootPath = join(this.#rootDir, id)
    try {
      await mkdir(rootPath, { recursive: true })
    } catch (error) {
      throw this.#wrapIoFailure('create', error)
    }
    return this.#issue(id, rootPath)
  }

  async acquire(id: string): Promise<WorkspaceHandle> {
    this.#assertActive()
    if (!WORKSPACE_ID_PATTERN.test(id) || WINDOWS_RESERVED_IDS.test(id)) this.#failUnknownId(id)
    const rootPath = join(this.#rootDir, id)
    // lstat (not stat): symlinks under rootDir are classified unknown, never followed.
    let info: Awaited<ReturnType<typeof lstat>>
    try {
      info = await lstat(rootPath)
    } catch (error) {
      if ((error as NodeJS.ErrnoException)?.code === 'ENOENT') this.#failUnknownId(id)
      throw this.#wrapIoFailure('acquire', error)
    }
    if (info.isSymbolicLink() || !info.isDirectory()) this.#failUnknownId(id)
    return this.#issue(id, rootPath)
  }

  async release(handle: WorkspaceHandle): Promise<void> {
    this.#assertActive()
    const lease =
      typeof handle === 'object' && handle !== null ? this.#leases.get(handle) : undefined
    if (!lease) {
      throw new PandaError(
        PANDA_ERROR_CODES.contractWorkspaceInvalidHandle,
        'release() only accepts workspace handles issued by this provider',
      )
    }
    if (lease.released) {
      throw new PandaError(
        PANDA_ERROR_CODES.contractWorkspaceDoubleRelease,
        `workspace '${handle.id}' has already been released through this handle`,
      )
    }
    lease.released = true
  }

  // Idempotent: workspace state outlives the provider, so there is nothing to undo.
  async dispose(): Promise<void> {
    this.#disposed = true
  }

  // Every handle gets its own frozen capabilities copy — no shared mutable array.
  #issue(id: string, rootPath: string): WorkspaceHandle {
    const handle: WorkspaceHandle = Object.freeze({
      id,
      rootPath,
      capabilities: Object.freeze([...LOCAL_CAPABILITIES]),
    })
    this.#leases.set(handle, { released: false })
    return handle
  }

  #assertActive(): void {
    if (this.#disposed) {
      throw new PandaError(
        PANDA_ERROR_CODES.contractProviderDisposed,
        'workspace provider has been disposed and no longer serves workspaces',
      )
    }
  }

  #failUnknownId(id: string): never {
    throw new PandaError(PANDA_ERROR_CODES.contractWorkspaceUnknownId, `unknown workspace id '${id}'`)
  }

  #wrapIoFailure(operation: string, error: unknown): PandaError {
    return new PandaError(
      PANDA_ERROR_CODES.contractWorkspaceUnavailable,
      `workspace provider ${operation} failed on filesystem '${this.#rootDir}': ${error instanceof Error ? error.message : String(error)}`,
      { cause: error },
    )
  }
}
